version: "3.8"
services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
  springboot:
    build:
      context: ./Spring_backend
    depends_on:
      - redis
  nginx:
    build:
      context: ./Docker_nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - springboot
    
  