spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://web-database.c4e9ujqrk1xx.ap-northeast-2.rds.amazonaws.com:3306/movie?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&useUnicode=true
    username: Manager
    password: 123456
  redis:
    host: redis
    port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    root: info

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# $ echo 'spring-boot-security-jwt-tutorial-bj-spring-boot-security-jwt-tutorial' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWJqLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC10dXRvcmlhbAo=

payment:
  key: 3664861278068200
  secretKey: GhpUhh8JQHOe0wOe9aUki6O4Pi423r1dOEIIC0ICJzfwPDXmsigDy5px7kiaGkLc2dvR53Pg5emdiK23

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json